export const userPayment = {
  SELLER_PAYMENT_REQUEST: 'SELLER_PAYMENT_REQUEST',
  ADD_SELLER_PAYMENT_SUCCESS: 'ADD_SELLER_PAYMENT_SUCCESS',
  SELLER_PAYMENT_ERROR: 'SELLER_PAYMENT_ERROR ',
  REMOVE_NOTIFICATIONS: 'REMOVE_NOTIFICATIONS',
};
