export const HANDLE_PRODUCT_FORM_DATA_CHANGE = 'HANDLE_PRODUCT_FORM_DATA_CHANGE';
export const HANDLE_SELLER_FORM_DATA_CHANGE = 'HANDLE_SELLER_FORM_DATA_CHANGE';
export const ADD_PRODUCT = 'ADD_PRODUCT';
