export const userConst = {
  USER_SIGNUP_REQUEST: 'USER_SIGNUP_REQUEST',
  USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
  USER_SIGNUP_ERROR: 'USER_SIGNUP_ERROR',
  USER_SIGNIN_ERROR: 'USER_SIGNIN_ERROR',
  USER_CLOSE_ERROR_MSG: 'USER_CLOSE_ERROR_MSG',
  USER_SELLAR_ACCOUNT_SUCCESS: ' USER_SELLAR_ACCOUNT_SUCCESS',
};
